CREATE DATABASE IF NOT EXISTS cmm007;
USE cmm007;

CREATE TABLE IF NOT EXISTS recipemethod (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    chefname VARCHAR(50) NOT NULL,
    category VARCHAR(100) NOT NULL UNIQUE,
    Recipename VARCHAR(255) NOT NULL,
    Ingredients TEXT NOT NULL,
    Directions TEXT,
    image TEXT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS images (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    image TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recipes (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    chefname VARCHAR(50) NOT NULL,
    category VARCHAR(100) NOT NULL UNIQUE,
    cuisine TEXT NOT NULL,
    location TEXT ,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);